# Generated by Django 6.0.6 on 2026-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resource_url', models.URLField(help_text='Link to the free book, tutorial, or course')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
