# Generated by Django 6.0.6 on 2026-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='resource_url',
            field=models.URLField(),
        ),
    ]
